#Code generated by ChatGPT
from setuptools import setup, find_packages

setup(
    name="rest-service-downloader",  # Name of your library
    version="0.1.0",  # Initial version
    author="APSU GIS Center",
    author_email="cordellm@apsu.edu",
    description="Downloads features from an ArcGIS Server feature service.",
    long_description=open("readme.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/APSU-GIS-Center/REST-Service-Downloader",  # Repo URL
    packages=find_packages(),  # Automatically find subpackages
    install_requires=[
        # List dependencies here (e.g., "numpy>=1.21.0")
    ],
    classifiers=[
        "Programming Language :: Python :: 3",
        "Operating System :: OS Independent",
    ],
    python_requires=">=3.7",  # Minimum Python version
)
